### PR TITLE
require sharp 0.26.3

### PR DESCRIPTION
**Pull request by mutec**
the old version leads to some crashes under strange circumstances

### CODE REVIEW

**Comment by ZachHappel** [comment]
You've tested this updated version of sharp? The issues that you were having were resolved when you used it?

**Comment by kibotrel** [comment]
Can you please accept this PR @ZachHappel, your current package does not work with node 16 but @mutec fork does. If you could update your package on NPM as well it would be nice! Thanks

**Comment by ZachHappel** [comment]
Sure thing, @kibotrel

**Comment by kibotrel** [comment]
Thanks for your quick response. Can you publish the new version on npm as well? It would be nice!

**Comment by ZachHappel** [comment]
I apologize for the delay. Just updated it. I'm not currently using the package and therefore I won't be privy to any issues that may arise; like the one we are addressing here. If anything else comes up, let me know!

**Comment by kibotrel** [comment]
Better late than never ahah! Thanks

**Pull request merged**
